/armor_tracker:
  ros__parameters:
    program_mode: 0 # 0：哨兵模式，1：步兵模式
    target_frame: odom
    max_armor_distance: 10.0
    debug: true

    ekf:
      sigma2_q_xyz_max: 1.4
      sigma2_q_yaw_max: 1.3
      sigma2_q_xyz_min: 0.05
      sigma2_q_yaw_min: 0.06
     
      sigma2_q_r: 65.0

      r_x: 0.0007
      r_y: 0.0009
      r_z: 0.001
      r_yaw: 0.0036

    tracker:
      max_match_distance_near: 0.6
      max_match_yaw_diff_near: 0.8
      max_match_distance_far: 0.7
      max_match_yaw_diff_far: 0.6


      tracking_thres: 1
      lost_time_thres: 0.6