/armor_tracker:
  ros__parameters:
    program_mode: 0 # 0：哨兵模式，1：步兵模式
    target_frame: odom
    max_armor_distance: 10.0
    debug: true

    ArmorModel:
      s2qx_: 10.0
      s2qy_: 10.0
      s2qz_: 10.0
      s2qyaw_: 10.0

      r_x_: 0.0001
      r_y_: 0.0001
      r_z_: 0.0001
      r_yaw_: 0.0001

      position_diff_thres: 0.2
      lost_time_thres: 0.3

      tracking_thres: 3
    
    EnemyModel:
      s2qxy_max_: 10.0
      s2qxy_min_: 0.05
      s2qz_: 10.0
      s2qyaw_max_: 10.0
      s2qyaw_min_: 0.05
      s2qr_: 10.0

      r_pose_: 0.0001
      r_distance_: 0.0001
      r_yaw_: 0.0001

      lost_time_thres: 0.3

      tracking_thres: 1