std_msgs/Header header
float32 pitch
float32 yaw
float32 shoot_speed
int32 current_color
###### 哨兵专有 ######
float32 big_yaw
int32 enemies_blood_0
int32 enemies_blood_1
int32 enemies_blood_2
int32 enemies_blood_3
int32 enemies_blood_4
int32 enemies_blood_5
int32 enemies_outpost
int32 another_priority 
int32 game_progress
int32 game_type
int32 if_attack_engineer
####################
int32 mode # 用于区分自瞄还是大符模式

